pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE_NAME = 'notes-frontend'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        GIT_REPO_URL = 'https://github.com/NomadStormbreaker/three-tier-notes.git'
        GIT_BRANCH = 'main'
        DEPLOYMENT_FILE_PATH = 'k8s-manifests/frontend/frontend-deployment.yaml'
        GIT_USER_EMAIL = 'chetanmirashi7@gmail.com'
        GIT_USER_NAME = 'NomadStormbreaker'
        GITHUB_TOKEN = credentials('github-cred')
        GIT_REPO_NAME = 'three-tier-notes'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    sh '''
                    pwd
                    ls -ltr
                    chmod +x Application-Code/scripts/build_and_push_frontend.sh
                    DOCKERHUB_USERNAME=${DOCKERHUB_CREDENTIALS_USR} \
                    DOCKERHUB_PASSWORD=${DOCKERHUB_CREDENTIALS_PSW} \
                    BUILD_NUMBER=${BUILD_NUMBER} \
                    ./Application-Code/scripts/build_and_push_frontend.sh
                    '''
                }
            }
        }

        stage('Update Kubernetes Deployment') {
            steps {
                script {
                    // Clone the repository containing the Kubernetes manifests
                    sh 'git clone -b ${GIT_BRANCH} ${GIT_REPO_URL} repo'
                    dir('repo') {
                        // Update the image tag in the frontend Kubernetes deployment file
                        sh '''
                        sed -i 's|\\(image: '"${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}"':\\)[^ ]*|\\1'"${BUILD_NUMBER}"'|' ${DEPLOYMENT_FILE_PATH}
                        git config user.email "${GIT_USER_EMAIL}"
                        git config user.name "${GIT_USER_NAME}"
                        git add ${DEPLOYMENT_FILE_PATH}
                        git commit -m "Update frontend image to ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:${GIT_BRANCH}
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Frontend Docker image built, pushed, and Kubernetes deployment updated successfully.'
        }
        failure {
            echo 'Failed to build, push the Docker image, or update the Kubernetes deployment.'
        }
    }
}
