pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE_NAME = 'notes-frontend'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    sh '''
                    pwd
                    ls -ltr
                    chmod +x Application-Code/scripts/build_and_push_frontend.sh
                    DOCKERHUB_USERNAME=${DOCKERHUB_CREDENTIALS_USR} \
                    DOCKERHUB_PASSWORD=${DOCKERHUB_CREDENTIALS_PSW} \
                    BUILD_NUMBER=${BUILD_NUMBER} \
                    ./Application-Code/scripts/build_and_push_frontend.sh
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image built and pushed successfully.'
        }
        failure {
            echo 'Failed to build or push the Docker image.'
        }
    }
}
