pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'notes-backend' // Replace with your desired Docker image name
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_creds') // Reference the credentials ID you created
        SONAR_URL = "http://54.234.119.1:9000" // Your SonarQube server URL
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Navigate to the backend directory and install dependencies
                    sh 'cd /Application-Code/backend && npm install'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                    cd /Application-Code/backend
                    sonar-scanner -Dsonar.projectKey=backend-project-key \
                                  -Dsonar.sources=. \
                                  -Dsonar.host.url=${SONAR_URL} \
                                  -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    // Use the credentials stored in Jenkins and run the script
                    sh '''
                    chmod +x /Application-Code/scripts/build_and_push.sh
                    DOCKERHUB_USERNAME=${DOCKERHUB_CREDENTIALS_USR} \
                    DOCKERHUB_PASSWORD=${DOCKERHUB_CREDENTIALS_PSW} \
                    BUILD_NUMBER=${BUILD_NUMBER} \
                    /Application-Code/scripts/build_and_push.sh
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image built and pushed successfully.'
        }
        failure {
            echo 'Failed to build or push the Docker image.'
        }
    }
}